### PR TITLE
Chartist & some charts

### PR DESCRIPTION
**Pull request by bnchdrff**

### CODE REVIEW

**Comment by hampelm** [comment]
Can you post a screenshot of what these look line on-page?

**Comment by bnchdrff** [comment]
screenshot from 2015-03-08 21 25 44
screenshot from 2015-03-08 21 24 58

**Comment by hampelm** [comment]
Pedantic-- is it possible to remove the decimals? eg `$100k` instead of `$100.0k`

**Comment by hampelm** [comment]
Now that we're presenting more aggregated numbers, we should note that these totals are based on our recorded grants, and not complete information. 

Maybe: 

> Based on records collected by the Ledger; may not be complete

or 

> Grant data may be incomplete

I'm fine opening this as a separate issue and merging the PR if there's not an obvious good choice for wording. 

(thanks to Rebecca for the feedback)

**Comment by bnchdrff** [comment]
i agree -- we do need to explain how the database works more thoroughly... let's address this in another issue though.

i removed that funny decimal place from the graphs & also removed the non-functioning tooltip code (see #78) -- let's merge!

**Pull request merged**
