### PR TITLE
Simple quality view

### PR DESCRIPTION
**Pull request by hampelm**
A first, super-ugly stab at a page that lists metrics for the Ledger that will help us improve. Currently counts orgs that: 

* Are missing a description, EIN, ntee, or tags
* haven't been edited in 270 days 

Also links to the edit page for 5 grants that match each of those problems so you can fix them!  A future version might have graphs, stats for grants, more explanatory text, etc.

Also drops `test-setup` from `gulp watch` for simplicity, tho I can remove that. 

screen shot 2015-01-24 at 2 22 13 pm

### CODE REVIEW

**Comment by hampelm** [comment]
oooo a future version will also sort those orgs by top grants received or given as a way to prioritize them

**Comment by bnchdrff** [comment]
:open_mouth: :candy: :fire:

**Comment by bnchdrff** [comment]
v fancy. i'll review+merge tonight. also, regarding the test/watch debacle, i'll cherry pick a fix i came up with in the chartist-browserify branch.

**Comment by hampelm** [comment]
the no_ntee list will probably need to be filtered to just nonprofits.

**Pull request merged**
